export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_ERROR = "GET_CONTACTS_ERROR";
export const GET_CONTACTS_PENDING = "GET_CONTACTS_PENDING";

export const GET_US_CONTACTS = "GET_US_CONTACTS";
export const GET_US_CONTACTS_SUCCESS = "GET_US_CONTACTS_SUCCESS";
export const GET_US_CONTACTS_ERROR = "GET_US_CONTACTS_ERROR";
export const GET_US_CONTACTS_PENDING = "GET_US_CONTACTS_PENDING";

export const GET_CONTACTS_SEARCH = "GET_CONTACTS_SEARCH";
export const GET_CONTACTS_SEARCH_SUCCESS = "GET_CONTACTS_SEARCH_SUCCESS";
export const GET_CONTACTS_SEARCH_ERROR = "GET_CONTACTS_SEARCH_ERROR";
export const GET_CONTACTS_SEARCH_PENDING = "GET_CONTACTS_SEARCH_PENDING";

export const GET_US_CONTACTS_SEARCH = "GET_US_CONTACTS_SEARCH";
export const GET_US_CONTACTS_SEARCH_SUCCESS = "GET_US_CONTACTS_SEARCH_SUCCESS";
export const GET_US_CONTACTS_SEARCH_ERROR = "GET_US_CONTACTS_SEARCH_ERROR";
export const GET_US_CONTACTS_SEARCH_PENDING = "GET_US_CONTACTS_SEARCH_PENDING";
